"""add bm25

Revision ID: 01bf6ee279f2
Revises: d62d79146a48
Create Date: 2026-08-12 21:40:15.967864

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01bf6ee279f2'
down_revision: Union[str, Sequence[str], None] = 'd62d79146a48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analyses', 'prompt_template',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_index(op.f('ix_analyses_document_created_at'), table_name='analyses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_analyses_document_created_at'), 'analyses', ['document_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('analyses', 'prompt_template',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
