"""added cascade in audit

Revision ID: 447f6ca51029
Revises: 281e5a3eeabe
Create Date: 2026-08-14 09:54:59.086828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '447f6ca51029'
down_revision: Union[str, Sequence[str], None] = '281e5a3eeabe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('audit_events_document_id_fkey'), 'audit_events', type_='foreignkey')
    op.drop_constraint(op.f('audit_events_analysis_id_fkey'), 'audit_events', type_='foreignkey')
    op.create_foreign_key(None, 'audit_events', 'documents', ['document_id'], ['document_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'audit_events', 'analyses', ['analysis_id'], ['analysis_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_events', type_='foreignkey')
    op.drop_constraint(None, 'audit_events', type_='foreignkey')
    op.create_foreign_key(op.f('audit_events_analysis_id_fkey'), 'audit_events', 'analyses', ['analysis_id'], ['analysis_id'])
    op.create_foreign_key(op.f('audit_events_document_id_fkey'), 'audit_events', 'documents', ['document_id'], ['document_id'])
    # ### end Alembic commands ###
