"""add analysis error message

Revision ID: 7cbabf818731
Revises: a7193e1eabd0
Create Date: 2026-08-11 12:11:17.792205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cbabf818731'
down_revision: Union[str, Sequence[str], None] = 'a7193e1eabd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('analyses', sa.Column('retry_count', sa.Integer(), nullable=False,server_default="0"))
    op.add_column('analyses', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('analyses', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.alter_column('analyses', 'raw_output',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('analyses', 'summary',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('analyses_document_created_idx'), table_name='analyses')
    op.drop_index(op.f('uq_active_analysis_per_document'), table_name='analyses', postgresql_where="(status = ANY (ARRAY['ANALYZING'::analysisstatus, 'CHUNKING'::analysisstatus, 'EMBEDDING'::analysisstatus]))")
    op.drop_constraint(op.f('analyses_document_id_fkey'), 'analyses', type_='foreignkey')
    op.create_foreign_key(None, 'analyses', 'documents', ['document_id'], ['document_id'], ondelete='CASCADE')
    op.alter_column('chat_documents', 'message_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('chunks', sa.Column('page_number', sa.Integer(), nullable=False, server_default="0"))
    op.alter_column('chunks', 'entities',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('chunks', 'notes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'notes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('chunks', 'entities',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('chunks', 'page_number')
    op.alter_column('chat_documents', 'message_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'analyses', type_='foreignkey')
    op.create_foreign_key(op.f('analyses_document_id_fkey'), 'analyses', 'documents', ['document_id'], ['document_id'])
    op.create_index(op.f('uq_active_analysis_per_document'), 'analyses', ['document_id'], unique=True, postgresql_where="(status = ANY (ARRAY['ANALYZING'::analysisstatus, 'CHUNKING'::analysisstatus, 'EMBEDDING'::analysisstatus]))")
    op.create_index(op.f('analyses_document_created_idx'), 'analyses', ['document_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('analyses', 'summary',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('analyses', 'raw_output',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('analyses', 'completed_at')
    op.drop_column('analyses', 'started_at')
    op.drop_column('analyses', 'retry_count')
    op.drop_column('analyses', 'error_message')
    # ### end Alembic commands ###
