"""made chunk.embedding nullable

Revision ID: 87c6eaf8fc69
Revises: d7429d5ccbc6
Create Date: 2026-08-08 01:18:57.604482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87c6eaf8fc69'
down_revision: Union[str, Sequence[str], None] = 'd7429d5ccbc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
