"""describe change

Revision ID: 8cbea3aff52b
Revises: e8467654cfdd
Create Date: 2026-08-07 09:11:12.832637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cbea3aff52b'
down_revision: Union[str, Sequence[str], None] = 'e8467654cfdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_documents', sa.Column('message_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'chat_documents', 'chat_messages', ['message_id'], ['message_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_documents', type_='foreignkey')
    op.drop_column('chat_documents', 'message_id')
    # ### end Alembic commands ###
