"""check for missing changes

Revision ID: 9621248075e7
Revises: 3549c10f803d
Create Date: 2026-08-14 11:22:24.574803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9621248075e7'
down_revision: Union[str, Sequence[str], None] = '3549c10f803d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('analyses_document_id_fkey'), 'analyses', type_='foreignkey')
    op.create_foreign_key(None, 'analyses', 'documents', ['document_id'], ['document_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analyses', type_='foreignkey')
    op.create_foreign_key(op.f('analyses_document_id_fkey'), 'analyses', 'documents', ['document_id'], ['document_id'])
    # ### end Alembic commands ###
