"""made chunk.embedding nullable

Revision ID: d7429d5ccbc6
Revises: 329cdc3eef8b
Create Date: 2026-08-08 01:18:36.041928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7429d5ccbc6'
down_revision: Union[str, Sequence[str], None] = '329cdc3eef8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
