"""create analysis table

Revision ID: e8467654cfdd
Revises: 46342948017a
Create Date: 2026-08-06 19:04:55.228695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8467654cfdd'
down_revision: Union[str, Sequence[str], None] = '46342948017a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analyses', 'raw_output',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('analyses', 'summary',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analyses', 'summary',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('analyses', 'raw_output',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
